AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Dakobed Rest API Service
Parameters:
  QueueName:
    Type: String
    Default: LibrosaTransformsQueue
  BucketName:
    Type: String
    Default: dakobed-sqs-transform-bucket
Resources:
  UploadApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: UploadApi
      StageName: Prod
      DefinitionUri: s3://dakobed-serverless-apis/49d74cbd7e9e4912ccb55dc6f7349db6
  PresignedPostUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      FunctionName: PresignedPostUploadFunction
      Policies:
      - S3CrudPolicy:
          BucketName:
            Ref: BucketName
      - SQSSendMessagePolicy:
          QueueName: InitiateTransformsQueue
      - AWSLambdaBasicExecutionRole
      - DynamoDBCrudPolicy:
          TableName: UserUploads
      CodeUri: s3://dakobed-serverless-apis/80d8b2ea0e71e85c9c464c9b1c8917bd
      Layers:
      - Fn::ImportValue: upload-authorization-layer-stack:AuthorizationLayer
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          userpool_id:
            Fn::ImportValue: upload-userpool-stack:UserPool
          app_client_id:
            Fn::ImportValue: upload-userpool-stack:UserPoolClient
          UploadBucket:
            Ref: BucketName
      Events:
        UploadApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: UploadApi
            Path: /signedURL
            Method: POST
  InsertUploadDynamoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      FunctionName: InsertUploadDynamoFunction
      Policies:
      - DynamoDBCrudPolicy:
          TableName: UserUploads
      CodeUri: s3://dakobed-serverless-apis/6b01e638a28b27e0d3523c8f291dab8f
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          UploadBucket:
            Ref: BucketName
      Events:
        UploadApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: UploadApi
            Path: /upload
            Method: POST
  ConfigLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
    - UploadApi
    - PresignedPostUploadFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: PresignedPostUploadFunction
      Principal: apigateway.amazonaws.com
  S3UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: BucketName
      NotificationConfiguration:
        QueueConfigurations:
        - Event: s3:ObjectCreated:Post
          Queue:
            Fn::GetAtt:
            - TransformQueue
            - Arn
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
          - '*'
          AllowedMethods:
          - GET
          - PUT
          - HEAD
          - POST
          AllowedOrigins:
          - '*'
  TransformQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        Ref: QueueName
  SQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    DependsOn: TransformQueue
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS: '*'
          Action: SQS:SendMessage
          Resource: '*'
          Condition:
            ArnLike:
              aws:SourceArn:
                Fn::Sub: arn:aws:s3:::${BucketName}
      Queues:
      - Ref: TransformQueue
