AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  query-ap
  Sample SAM Template for query-api

Parameters:
  AuthorizationLayerName:
    Type: String
    Default: upload-authorization-layer

Resources:
  AuthorizationLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Ref AuthorizationLayerName
      ContentUri: py-jose.zip
      CompatibleRuntimes:
        - python3.7
    Metadata:
      BuildMethod: python3.7


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AuthorizationLayer:
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'AuthorizationLayer' ] ]
    Value: !Ref AuthorizationLayer

